<?php
/**
 * GET /api/status — what this deployment can and cannot do.
 *
 * The front-end uses this to decide whether to offer a live audit at all, and
 * to render the runtime banner. Module and check counts are baked in from the
 * canonical registry at build time (never hand-maintained here), and the list
 * of static reports is read from reports/index.json if the operator published
 * one with the canonical Python renderer.
 */

declare(strict_types=1);

require_once __DIR__ . '/_bootstrap.php';

ope_require_method('GET', 'HEAD');

/**
 * Report descriptors published alongside the shell.
 *
 * reports/index.json is generated by the canonical engine (see the deployment
 * doc); it is read as data and every field is passed through untouched. If it is
 * absent or malformed, an empty list is reported rather than an invented one.
 */
function ope_published_reports(): array
{
    $path = dirname(__DIR__) . '/reports/index.json';
    if (!is_file($path)) {
        return [];
    }
    $raw = file_get_contents($path, false, null, 0, 262144);
    if ($raw === false) {
        return [];
    }
    try {
        $decoded = json_decode($raw, true, 8, JSON_THROW_ON_ERROR);
    } catch (JsonException) {
        return [];
    }
    if (!is_array($decoded)) {
        return [];
    }
    $items = is_array($decoded['reports'] ?? null) ? $decoded['reports'] : $decoded;
    $out = [];
    foreach ($items as $item) {
        if (!is_array($item)) {
            continue;
        }
        $file = isset($item['file']) && is_string($item['file']) ? basename($item['file']) : null;
        if ($file === null || $file === '') {
            continue;
        }
        $out[] = [
            'file' => $file,
            'target' => isset($item['target']) && is_string($item['target']) ? $item['target'] : null,
            'generated_at' => isset($item['generated_at']) && is_string($item['generated_at']) ? $item['generated_at'] : null,
            'engine_version' => isset($item['engine_version']) && is_string($item['engine_version']) ? $item['engine_version'] : null,
        ];
    }
    return $out;
}

$live = ope_has_live_runtime();
ope_json([
    'status' => 'ok',
    'web_contract' => OPE_WEB_CONTRACT_VERSION,
    'engine' => OPE_ENGINE,
    'engine_version' => OPE_ENGINE_VERSION,
    'runtime' => ope_runtime(),
    'live_execution' => $live,
    'module_count' => OPE_MODULE_COUNT,
    'check_count' => OPE_CHECK_COUNT,
    'message' => $live ? null : OPE_RUNTIME_UNAVAILABLE_MESSAGE,
    'capabilities' => [
        // What this runtime can actually do — stated plainly, no optimism.
        'static_command_center' => true,
        'render_existing_reports' => true,
        'upload_report_json' => true,
        'live_audit' => $live,
    ],
    'reports' => ope_published_reports(),
]);
