"""Standalone HTML site-audit reports using the RawBlock design system.

Reuses shared helpers from report_html.py. The report extends the
single-page template with site-level sections (crawl summary, link
graph statistics, cross-page findings).
"""
from __future__ import annotations

import os
from pathlib import Path
from typing import Any

from .report_html import (
    _e,
    _finding_card,
    _iso,
    _module_grid,
    _status_chip,
    _summary_cards,
    load_rawblock_css,
)


def _crawl_summary_cards(result: dict[str, Any]) -> str:
    crawl = result.get("crawl_summary", {})
    if not isinstance(crawl, dict):
        crawl = {}
    items = [
        ("Pages crawled", crawl.get("pages_crawled", 0)),
        ("Depth reached", crawl.get("max_depth_reached", 0)),
        ("Internal links", crawl.get("internal_links", 0)),
        ("External links", crawl.get("external_links", 0)),
        ("Orphan pages", crawl.get("orphan_pages", 0)),
        ("Errors", crawl.get("error_count", 0)),
    ]
    cells = []
    for label, value in items:
        elevated = " rb-card--elevated" if label == "Errors" and value else ""
        color = ' class="rb-txt-error"' if label == "Errors" and value else ""
        cells.append(
            f'<div class="rb-card{elevated}" style="text-align:center;padding:var(--rb-sp-3);">'
            f'<div class="rb-mono rb-tiny rb-uppercase">{_e(label)}</div>'
            f'<div style="font-family:var(--rb-font-headline);font-size:48px;line-height:1.1;"'
            f'{color}>{value}</div></div>'
        )
    return '<div class="rb-grid rb-grid-3" style="margin-bottom:var(--rb-sp-5);">' + "".join(cells) + "</div>"


def _page_table(result: dict[str, Any]) -> str:
    pages = result.get("pages", [])
    if not isinstance(pages, list) or not pages:
        return ""
    rows = []
    for page in pages[:50]:
        if not isinstance(page, dict):
            continue
        url = _e(page.get("url", ""))
        status = page.get("status_code", "?")
        depth = page.get("depth", "?")
        finding_count = len(page.get("findings", []))
        rows.append(
            f"<tr><td><code>{url}</code></td>"
            f"<td>{_e(status)}</td>"
            f"<td>{_e(depth)}</td>"
            f"<td>{finding_count}</td></tr>"
        )
    if not rows:
        return ""
    return (
        '<details style="margin-bottom:var(--rb-sp-5);">'
        '<summary class="rb-btn rb-btn--sm rb-btn--secondary" style="display:inline-flex;">'
        f"PAGES ({len(pages)} total)</summary>"
        '<table class="rb-table" style="margin-top:var(--rb-sp-3);">'
        "<thead><tr><th>URL</th><th>Status</th><th>Depth</th><th>Findings</th></tr></thead>"
        "<tbody>" + "".join(rows) + "</tbody></table></details>"
    )


def site_html_report(result: dict[str, Any]) -> str:
    """Render a normalized site audit result as a standalone RawBlock HTML document."""
    css = load_rawblock_css()
    summary = result.get("summary", {})
    modules = result.get("modules", {})
    findings = sorted(
        result.get("findings", []),
        key=lambda f: float(f.get("priority", 0.0)),
        reverse=True,
    )

    status = result.get("status", "UNKNOWN")
    status_chip = _status_chip(status)

    finding_cards = "".join(_finding_card(f) for f in findings) or (
        '<div class="rb-card rb-card--elevated"><h3 class="rb-card__title">NO FINDINGS</h3>'
        "<p>No site-level findings were generated by the deterministic checks.</p></div>"
    )

    filters = ["ALL", "CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]
    filter_buttons = "".join(
        f'<button class="rb-chip rb-filter{" is-active" if f == "ALL" else ""}" type="button" '
        f'data-filter="{f.lower()}" aria-pressed="{str(f == "ALL").lower()}">{f}</button>'
        for f in filters
    )

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>OPE // SITE AUDIT — {_e(result.get('target', ''))}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Archivo+Black&family=Space+Mono:wght@400;700&family=Work+Sans:wght@400;500;600&display=swap" rel="stylesheet">
<style>
{css}
.report-header {{ border-bottom: var(--rb-border-heavy); }}
.meta-bar {{ display:flex; flex-wrap:wrap; gap:var(--rb-sp-3); align-items:center; }}
</style>
</head>
<body>

<header class="report-header rb-inverted">
  <div class="rb-shell" style="padding-top:var(--rb-sp-4);padding-bottom:var(--rb-sp-4);">
    <p class="rb-mono rb-tiny rb-uppercase" style="margin-bottom:var(--rb-sp-2);">
      OMNI-PRESENCE ENGINE · SITE AUDIT · RAW//BLOCK REPORT
    </p>
    <h1 style="font-size:clamp(32px,6vw,64px);margin:0;">{_e(result.get('target', ''))}</h1>
    <div class="meta-bar" style="margin-top:var(--rb-sp-3);">
      {status_chip}
      <span class="rb-chip rb-chip--status">SCOPE: SITE</span>
      <span class="rb-mono rb-tiny">{_iso(result.get('started_at', 0))}</span>
    </div>
  </div>
</header>

<main class="rb-shell" style="padding-top:var(--rb-sp-5);padding-bottom:var(--rb-sp-7);">

  <h2>CRAWL SUMMARY</h2>
  {_crawl_summary_cards(result)}

  {_page_table(result)}

  <h2>FINDING SUMMARY</h2>
  {_summary_cards(summary)}

  <h2>MODULES (20-LAYER DEPENDENCY GRAPH)</h2>
  {_module_grid(modules)}

  <div style="display:flex;flex-wrap:wrap;align-items:baseline;gap:var(--rb-sp-3);">
    <h2 style="margin:0;">FINDINGS</h2>
    <span style="flex:1 1 auto;"></span>
    <span class="row rb-stack" style="display:flex;gap:8px;flex-wrap:wrap;">{filter_buttons}</span>
  </div>
  <hr class="rb-rule">
  <div id="findings">{finding_cards}</div>

</main>

<footer style="border-top:var(--rb-border-heavy);">
  <div class="rb-shell rb-inverted" style="border:0;padding-top:var(--rb-sp-4);padding-bottom:var(--rb-sp-4);">
    <p class="rb-mono rb-tiny" style="margin:0;">
      GENERATED BY OPE {_e(result.get('version', ''))} · CONTRACT {_e(result.get('engine_contract', 'evidence-diagnostic-v1'))} ·
      SCOPE {_e(result.get('engine_scope', 'site'))} · EVIDENCE IS DIRECT · RAW//BLOCK DESIGN SYSTEM
    </p>
  </div>
</footer>

<script>
  document.querySelectorAll('.rb-filter').forEach(function (btn) {{
    btn.addEventListener('click', function () {{
      document.querySelectorAll('.rb-filter').forEach(function (b) {{
        b.classList.remove('is-active');
        b.setAttribute('aria-pressed', 'false');
      }});
      btn.classList.add('is-active');
      btn.setAttribute('aria-pressed', 'true');
      var want = btn.getAttribute('data-filter');
      document.querySelectorAll('.rb-finding').forEach(function (card) {{
        card.style.display = (want === 'all' || card.getAttribute('data-severity') === want) ? '' : 'none';
      }});
    }});
  }});
</script>
</body>
</html>
"""


def write_site_html_report(result: dict[str, Any], path: str | os.PathLike[str]) -> Path:
    """Render and persist the site audit report; returns the written path."""
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(site_html_report(result), encoding="utf-8")
    return out
